version: "2.1"
services:
  antidote1:
    image: itoumlilt/antidotedb:v0.2.0-alpine-iptables
    ports:
     - "127.0.0.1:8087:8087"
    environment:
      NODE_NAME: "antidote@antidote1"
      SHORT_NAME: "true"

  antidote2:
    image: itoumlilt/antidotedb:v0.2.0-alpine-iptables
    ports:
     - "127.0.0.1:8088:8087"
    environment:
      NODE_NAME: "antidote@antidote2"
      SHORT_NAME: "true"
      
  antidote3:
    image: itoumlilt/antidotedb:v0.2.0-alpine-iptables
    ports:
     - "127.0.0.1:8089:8087"
    environment:
      NODE_NAME: "antidote@antidote3"
      SHORT_NAME: "true"

  link:
    image: erlang:21-slim
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/ready"]
      interval: 3s
      timeout: 1s
      retries: 10
    volumes:
      - .:/code
    command: '/code/connect_dcs.sh'
    links:
      - antidote1
      - antidote2
      - antidote3
